### ISSUE TITLE
problems installing

### ISSUE THREAD

**Issue by mattvenn** [algernon/Chrysalis#31]
I'm trying to install the new clojurescript version and after successfully installing the dependancies and running foreman I get this:

```
mattsmac:2032 [master]: foreman start
14:11:05 electron.1 | started with pid 16191
14:11:05 ui.1       | started with pid 16193
14:11:09 ui.1       | Figwheel: Cutting some fruit, just a sec ...
14:11:10 electron.1 | Watching for changes before compiling ClojureScript...
14:11:13 ui.1       | Exception in thread "main" java.util.regex.PatternSyntaxException: Unknown inline modifier near index 2
14:11:13 ui.1       | (?U)^[\p{Alpha}_$]
14:11:13 ui.1       |   ^, compiling:(cljs/util.cljc:181:33)
14:11:13 ui.1       |   at clojure.lang.Compiler.load(Compiler.java:7386)
```

**Comment by algernon** [comment]
Wow, this is interesting. What version of Java do you have?

**Comment by mattvenn** [comment]
Old, probably:
```
java version "1.6.0_35"
OpenJDK Runtime Environment (IcedTea6 1.13.7) (6b35-1.13.7-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
```
Is java used for the clojure -> javascript process?

**Comment by algernon** [comment]
Aha, therein lies the problem, the ClojureScript compiler requires Java 7 (recommends 8, but I'm doing development with Java 7).

And yep, Java is used for the ClojureScript->JavaScript process, the CLJS compiler is in Clojure, which is what needs the Java bits.

**Comment by mattvenn** [comment]
got a new one, after copying lein to /usr/local/bin 
lein npm run start-backend works fine
then lein npm run start-ui complains with:
Your project already has a package.json file.  Please remove it.

there is no package.json in the root dir, this is a relatively new clone of master.

**Comment by algernon** [comment]
oh, yeah. that one I still need to fix. `lein npm` creates a temporary `package.json` in `resources/public`. Delete that before running `lein npm run start-ui`, and it should be okay. I'll figure out a better solution soon!
