### ISSUE TITLE
Home screen

### ISSUE THREAD

**Issue by algernon** [algernon/Chrysalis#4]
The home screen should be the main entry point, where we display the detected device(s), and offer links to the various functionality of the application.

It should be preceded by a loading/detection screen, while devices are scanned.

**Comment by algernon** [comment]
Just had a terrific idea! Seeking input from @TheBaronHimself on this one.

How about if we have more than the detect => home screen step? What if we did a detect, offered a list of devices for the user to select from (auto-selects if there is only one device), and THEN offer the home screen links?

So we could have a screen where we have a Chrysalis logo, a list of devices underneath (with the active one highlighted), and then the real menu under that?

**Comment by TheBaronHimself** [comment]
Sounds good to me :). Regarding home screen: I think we should work with tabs for quick navigation (see screenshot as example).

![screen shot 2017-04-14 at 11 54 06](https://cloud.githubusercontent.com/assets/11179011/25040378/3afd709e-2109-11e7-980d-4ee6d9694d65.png)



If we only gave users access to different pages from home screen links they'd have to click an awful lot more, e.g. Home screen -> *click to access keymap editor* -> *do things in keymap editor* -> *click 'back to home screen' button* -> *click REPL button*

If we had a home tab, a keymap editor tab and a REPL tab only one click would be required to switch between them and we wouldn't have the static sidebar issue you mentioned somewhere.

Thoughts?

**Comment by algernon** [comment]
That sounds like a good idea. And then the Home screen could host the device selector, so it wouldn't feel too empty. Nor would it be too crowded.

**Comment by algernon** [comment]
Went with a navbar instead, that felt better. If it turns out to be a bad idea, we can easily replace it.

The home screen is looking quite okay now, so closing this! (We'll definitely want to improve it further, mind you, but lets do that as specific tasks)
