### ISSUE TITLE
SVG for the virtual device

### ISSUE THREAD

**Issue by algernon** [algernon/Chrysalis#55]
For the new `LED theme editor` (and other features in the future) to work, we'll need a layout for each device. For the Model01, there already was one, but for the virtual device, we still need one.

It is a 4x4 key device, an SVG that has a keypad-like thing in a 4x4 setting would do. It should be set up so that the fillable areas have ids like `RxCy_F`, just like the Model01's SVG. The image should be placed in `lib/chrysalis/plugin/hardware/virtual/`, and a reference added to the `core.cljs` file, see [here](https://github.com/algernon/Chrysalis/blob/c7a553a36854c7d5903b02508f2254e72a21e5c9/src/chrysalis/plugin/hardware/model01/core.cljs#L24) for an example.

**Comment by TheBaronHimself** [comment]
Quick note: Added the SVG and the reference. IDs are still missing. Coming soon.
