### ISSUE TITLE
SVG for the Shortcut

### ISSUE THREAD

**Issue by algernon** [algernon/Chrysalis#56]
For the new `LED theme editor` (and other features in the future) to work, we'll need a layout for each device. For the Model01, there already was one, but for the [Shortcut](http://shortcut.gg), we still need one.

It should be set up so that the fillable areas have ids like `RxCy_F`, just like the Model01's SVG. The image should be placed in `lib/chrysalis/plugin/hardware/virtual/`, and a reference added to the `core.cljs` file, see [here](https://github.com/algernon/Chrysalis/blob/c7a553a36854c7d5903b02508f2254e72a21e5c9/src/chrysalis/plugin/hardware/model01/core.cljs#L24) for an example.

Something like [this](http://www.keyboard-layout-editor.com/#/gists/c41961aa970d730b37636bd04941e318) may be a reasonable starting point.

**Comment by TheBaronHimself** [comment]
Done. 

- 6e9e9218b28cbc8c44beb753b80466793648f629
- 05d937646f75760892c9345b9589a8f16258e07a

PNGs are still placeholders, see https://github.com/algernon/Chrysalis/issues/73.
