### ISSUE TITLE
Add an "About" dialog

### ISSUE THREAD

**Issue by algernon** [algernon/Chrysalis#62]
The `Chrysalis` menu should have an `About` menu item, which pops up a dialog with some basic information about Chrysalis:

- Logo, name, version
- Authors
- License

For the user, the most important part here will be the version.

**Comment by algernon** [comment]
On second thought, how about this:

A logo, that links to the git repo (later homepage), below it, a version, and a link to the release notes (on github). On the third line, a license button. And at the bottom, a built-by blurb (linking back to the contributor tab here on GitHub).

**Comment by TheBaronHimself** [comment]
Where exactly do you imagine this would be placed?

**Comment by algernon** [comment]
The dialog itself would be a modal, its display triggered from the main menu (kinda like the `Settings` placeholder at the moment).
