### ISSUE TITLE
install issue on linux

### ISSUE THREAD

**Issue by mattvenn** [algernon/Chrysalis#63]
lein deps fails with

```
node-pre-gyp ERR! Tried to download: https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@6.10.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
```

[Releases of usb library](https://github.com/tessel/node-usb/releases) show only windows and darwin releases available.

Local build fails because of missing libudev on my system. How can this dependency be added?

fixed with 

`sudo apt-get install libudev-dev`

**Comment by mattvenn** [comment]
lein build completes with no errors, but 
lein start-ui results in this:

`venv)mattsmac:2140 [master]: lein start-ui

> Chrysalis@0.1.0-SNAPSHOT start-ui /home/mattvenn/work/shortcut/v5-firmware/Chrysalis2/resources/public
> electron ..

/home/mattvenn/work/shortcut/v5-firmware/Chrysalis2/resources/public/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/home/mattvenn/work/shortcut/v5-firmware/Chrysalis2/resources/public/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mattvenn/work/shortcut/v5-firmware/Chrysalis2/resources/public/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:570:32)

npm ERR! Linux 3.13.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start-ui"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Chrysalis@0.1.0-SNAPSHOT start-ui: `electron ..`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Chrysalis@0.1.0-SNAPSHOT start-ui script 'electron ..'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Chrysalis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron ..
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Chrysalis
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Chrysalis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mattvenn/work/shortcut/v5-firmware/Chrysalis2/resources/public/npm-debug.log
`

**Comment by algernon** [comment]
Interesting, looks like electron failed to install correctly for some reason... hrm. Can you try removing `resources/public/node_modules/electron`, and then `lein npm install`?

**Comment by mattvenn** [comment]
That did the trick, thanks. Nice to see how things are shaping up!
