### ISSUE TITLE
ui: Rethink the main menu

### ISSUE THREAD

**Issue by algernon** [algernon/Chrysalis#71]
The main menu at the moment is a horizontal bar at the top. We are going to have a bunch of more components, and the list will simply not fit. Or if it will, it will be terribly long and awkward, especially with long, explanatory titles.

Instead, we should shovel them into the "Chrysalis" menu, where the dropdown would trigger a sidebar instead of a dropdown menu. We could have the pages there, vertically, with better titles.

The current page title then would move to the top bar, to the right of the Chrysalis menu.

**Comment by marcus7777** [comment]
You up for using a framework like polymer?

**Comment by algernon** [comment]
Mmmm... not sure. I'm not familiar with frontend technologies, so I have almost no idea what Polymer is (I had a quick glance at their website). At the moment, I'm using React (via the Reagent ClojureScript library), and that's serving me well. I'm also looking into [re-frame](https://github.com/Day8/re-frame), because that seems to fit the needs of Chrysalis fairly well.

At this point, I'd only consider a framework, if it builds on React, and has a decent ClojureScript library too. Otherwise the current status quo is sufficient, I just need to learn how to make a usable UI (but that is pretty much independent on any framework or library).

**Comment by marcus7777** [comment]
Thanks
